import Head from 'next/head'
import BarRoutesUser from '@/components/barRoutesUser'
import { Container } from '@mui/system'
import { Grid, Paper } from '@mui/material'
import CardRoute from '@/components/cardRoute'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BarRoutesUser sx={{mb: 2}}></BarRoutesUser> 
      <Paper>
        <Container>
          <Grid container spacing={2}>
            <Grid item xs={12} md={4} xl={2}>
              <CardRoute></CardRoute> 
            </Grid>
          </Grid>
        </Container>
      </Paper>
    </>
  )
}
